name = "chutes-tps-leaderboard"
main = "src/index.ts"
compatibility_date = "2024-12-01"

assets = { directory = "./public" }

[[d1_databases]]
binding = "DB"
database_name = "chutes-leaderboard"
database_id = "1f265053-1371-452b-89c5-7b40a815c694"

[triggers]
crons = ["*/10 * * * *"]
